baseURL = "/"
languageCode = "en-us"
title = "Banana's Blog"
theme="archie"
copyright = "© 1337Bananas"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=10 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A site for Blockchain x Cyber musings - Gone Bananas"
	favicon = "favicon.svg"

# Social Tags

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/1337bananas"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3